# Generated by Django 4.0.2 on 2023-06-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_drughour_id_remove_drughour_prescdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='maxDoseHours',
        ),
        migrations.AddField(
            model_name='drughour',
            name='id',
            field=models.BigAutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(db_column='userId', default=5, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drughour',
            name='schedule',
            field=models.ForeignKey(db_column='schedule', on_delete=django.db.models.deletion.CASCADE, related_name='drugHour', to='users.schedule'),
        ),
    ]
